# syntax=docker/dockerfile:1

FROM node:20-alpine AS builder

WORKDIR /app

ARG VITE_API_URL=http://localhost:4000/api
ARG VITE_SOCKET_URL=http://localhost:4000
ARG VITE_APP_URL=http://localhost:3000
ARG VITE_META_APP_ID=
ARG VITE_META_CONFIG_ID=
ARG VITE_META_WHATSAPP_CONFIG=
ARG VITE_META_EMBEDDED_REDIRECT_URI=
ARG VITE_META_OAUTH_REDIRECT_URI=
ARG VITE_META_INSTAGRAM_REDIRECT_URI=

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SOCKET_URL=$VITE_SOCKET_URL
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_META_APP_ID=$VITE_META_APP_ID
ENV VITE_META_CONFIG_ID=$VITE_META_CONFIG_ID
ENV VITE_META_WHATSAPP_CONFIG=$VITE_META_WHATSAPP_CONFIG
ENV VITE_META_EMBEDDED_REDIRECT_URI=$VITE_META_EMBEDDED_REDIRECT_URI
ENV VITE_META_OAUTH_REDIRECT_URI=$VITE_META_OAUTH_REDIRECT_URI
ENV VITE_META_INSTAGRAM_REDIRECT_URI=$VITE_META_INSTAGRAM_REDIRECT_URI

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine AS runner

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget -qO- http://127.0.0.1/ >/dev/null 2>&1 || exit 1

CMD ["nginx", "-g", "daemon off;"]
