import type { Lead, LeadRep } from './types';

const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 86400_000).toISOString();

export const MOCK_REPS: LeadRep[] = [
  { id: 'rep-1', name: 'Ananya', avatarUrl: 'https://i.pravatar.cc/80?u=ananya' },
  { id: 'rep-2', name: 'Vikram', avatarUrl: 'https://i.pravatar.cc/80?u=vikram' },
  { id: 'rep-3', name: 'Meera', avatarUrl: 'https://i.pravatar.cc/80?u=meera' },
];

/** Mock kanban data — replace with API later. */
export const MOCK_LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Priya Sharma',
    phone: '+91 98765 43210',
    email: 'priya@salon.co',
    stage: 'new',
    source: 'instagram',
    requirement: 'Needs 2 salon kit sets, Mumbai delivery',
    assignedRep: MOCK_REPS[0],
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(2),
    origin: {
      username: 'priya.sharma',
      commentText: 'This looks amazing! Do you deliver to Mumbai? Need 2 sets for my salon 🙌',
      postThumbnailUrl: 'https://picsum.photos/seed/cs-post1/200/200',
      postCaption: 'New summer collection drop — limited stock',
      commentedAt: hoursAgo(2.2),
    },
    notes: '',
    activity: [
      {
        id: 'a1',
        type: 'dm_sent',
        text: 'Auto-DM sent after review approval',
        at: hoursAgo(1.8),
      },
      { id: 'a2', type: 'created', text: 'Lead created from Instagram comment', at: hoursAgo(2) },
    ],
  },
  {
    id: 'lead-2',
    name: null,
    phone: null,
    email: null,
    stage: 'new',
    source: 'instagram',
    requirement: 'Asked for catalogue via comment',
    assignedRep: null,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(5),
    origin: {
      username: 'sneha.r',
      commentText: 'Interested! Please DM me the catalogue ✨',
      postThumbnailUrl: 'https://picsum.photos/seed/cs-post4/200/200',
      postCaption: 'Behind the scenes — factory tour',
      commentedAt: hoursAgo(5),
    },
    notes: 'Waiting for reply to DM',
    activity: [
      { id: 'a3', type: 'created', text: 'Lead created from Instagram comment', at: hoursAgo(5) },
    ],
  },
  {
    id: 'lead-3',
    name: 'Rahul Mehta',
    phone: '+91 99887 76655',
    email: null,
    stage: 'contacted',
    source: 'instagram',
    requirement: 'Wants pricing + COD for Pro skincare kit',
    assignedRep: MOCK_REPS[1],
    createdAt: hoursAgo(8),
    updatedAt: hoursAgo(3),
    origin: {
      username: 'rahul.mehta',
      commentText: 'Price please? And is COD available?',
      postThumbnailUrl: 'https://picsum.photos/seed/cs-post2/200/200',
      postCaption: 'Pro skincare kit — 30% off this week',
      commentedAt: hoursAgo(8),
    },
    notes: 'Sent price list on WhatsApp',
    activity: [
      {
        id: 'a4',
        type: 'stage_change',
        text: 'Moved from New → Contacted',
        at: hoursAgo(3),
      },
      { id: 'a5', type: 'dm_sent', text: 'DM with pricing sent', at: hoursAgo(6) },
      { id: 'a6', type: 'created', text: 'Lead created from Instagram comment', at: hoursAgo(8) },
    ],
  },
  {
    id: 'lead-4',
    name: 'Kavya Designs',
    phone: '+91 91234 56789',
    email: 'hello@kavyadesigns.in',
    stage: 'qualified',
    source: 'instagram',
    requirement: 'Boutique wholesale — 50+ units/month',
    assignedRep: MOCK_REPS[0],
    createdAt: daysAgo(2),
    updatedAt: hoursAgo(12),
    origin: {
      username: 'kavya.designs',
      commentText: 'Love the packaging! Can I bulk order for my boutique?',
      postThumbnailUrl: 'https://picsum.photos/seed/cs-post5/200/200',
      postCaption: 'Packaging glow-up 📦',
      commentedAt: daysAgo(2),
    },
    notes: 'Budget confirmed ~₹1.2L/mo',
    activity: [
      {
        id: 'a7',
        type: 'stage_change',
        text: 'Moved from Contacted → Qualified',
        at: hoursAgo(12),
      },
      { id: 'a8', type: 'note', text: 'Call completed — strong fit', at: hoursAgo(14) },
      { id: 'a9', type: 'created', text: 'Lead created from Instagram comment', at: daysAgo(2) },
    ],
  },
  {
    id: 'lead-5',
    name: 'Arjun Patel',
    phone: '+91 90000 11122',
    email: 'arjun@retailhub.com',
    stage: 'negotiation',
    source: 'manual',
    requirement: 'Distributor deal for Gujarat region',
    assignedRep: MOCK_REPS[2],
    createdAt: daysAgo(5),
    updatedAt: hoursAgo(6),
    origin: null,
    notes: 'Negotiating margin at 22%',
    activity: [
      {
        id: 'a10',
        type: 'stage_change',
        text: 'Moved from Qualified → Negotiation',
        at: hoursAgo(6),
      },
      { id: 'a11', type: 'created', text: 'Manually added by Meera', at: daysAgo(5) },
    ],
  },
  {
    id: 'lead-6',
    name: 'Sana Khan',
    phone: '+91 95555 44433',
    email: 'sana@gmail.com',
    stage: 'won',
    source: 'instagram',
    requirement: 'Bridal package — 1 set',
    assignedRep: MOCK_REPS[1],
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    origin: {
      username: 'sana.k',
      commentText: 'Need this for my wedding next month!',
      postThumbnailUrl: 'https://picsum.photos/seed/cs-post3/200/200',
      postCaption: 'Gentle cleanser — dermatologist recommended',
      commentedAt: daysAgo(10),
    },
    notes: 'Paid via UPI',
    activity: [
      { id: 'a12', type: 'stage_change', text: 'Moved from Negotiation → Won', at: daysAgo(1) },
      { id: 'a13', type: 'created', text: 'Lead created from Instagram comment', at: daysAgo(10) },
    ],
  },
  {
    id: 'lead-7',
    name: 'Dev Joshi',
    phone: null,
    email: 'dev@startup.io',
    stage: 'lost',
    source: 'whatsapp',
    requirement: 'Enterprise plan inquiry — budget mismatch',
    assignedRep: MOCK_REPS[2],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
    origin: null,
    notes: 'Chose competitor on price',
    activity: [
      { id: 'a14', type: 'stage_change', text: 'Moved from Qualified → Lost', at: daysAgo(3) },
      { id: 'a15', type: 'created', text: 'Inbound WhatsApp', at: daysAgo(14) },
    ],
  },
  {
    id: 'lead-8',
    name: 'Neha Kapoor',
    phone: '+91 97777 88899',
    email: null,
    stage: 'contacted',
    source: 'instagram',
    requirement: 'Dry-skin product fit question',
    assignedRep: MOCK_REPS[0],
    createdAt: hoursAgo(10),
    updatedAt: hoursAgo(4),
    origin: {
      username: 'neha.kapoor',
      commentText: 'Is this suitable for dry skin? My dermatologist said I need something gentle.',
      postThumbnailUrl: 'https://picsum.photos/seed/cs-post3/200/200',
      postCaption: 'Gentle cleanser — dermatologist recommended',
      commentedAt: hoursAgo(10),
    },
    notes: '',
    activity: [
      {
        id: 'a16',
        type: 'stage_change',
        text: 'Moved from New → Contacted',
        at: hoursAgo(4),
      },
      { id: 'a17', type: 'created', text: 'Lead created from Instagram comment', at: hoursAgo(10) },
    ],
  },
];
